language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install wget liblua5.1-dev libluajit-5.1-dev
  - git submodule init
  - git submodule update
  - wget http://jaist.dl.sourceforge.net/boost/boost_1_54_0.tar.bz2
  - tar -xf boost_1_54_0.tar.bz2
  - wget 'https://svn.boost.org/trac/boost/raw-attachment/ticket/8772/boost_1_54_0_variant.patch'
  - ( cd boost_1_54_0 && patch -p1 < ../boost_1_54_0_variant.patch )
  - ( cd boost_1_54_0 && ./bootstrap.sh --prefix=/usr --with-libraries=date_time,filesystem,exception,log,locale,random,regex,program_options,system,thread,timer,chrono )
  - ( cd boost_1_54_0 && sudo ./b2 -j2 link=static install ) > /dev/null

before_script:
  LDFLAGS="-lrt"  cmake -DENABLE_LUA=on  .

script:
  make

notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

